plugin:
    name: 'sqwk.gallery::lang.plugin.name'
    description: 'sqwk.gallery::lang.plugin.description'
    author: sqwk
    icon: oc-icon-picture-o
    homepage: ''
permissions:
    sqwk.gallery.manage_galleries:
        tab: 'sqwk.gallery::lang.plugin.name'
        label: 'sqwk.gallery::lang.plugin.permission'
navigation:
    gallery:
        label: 'sqwk.gallery::lang.plugin.name'
        url: sqwk/gallery/gallery
        icon: icon-picture-o
        permissions:
            - sqwk.gallery.manage_galleries
        sideMenu:
            headlines:
                label: 'sqwk.gallery::lang.sidemenu.galleries'
                url: sqwk/gallery/gallery
                icon: icon-picture-o